
package codes.uab.ats.soap_test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestWebService", targetNamespace = "http://soap_test.ats.uab.codes/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://soap_test.ats.uab.codes/", className = "codes.uab.ats.soap_test.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://soap_test.ats.uab.codes/", className = "codes.uab.ats.soap_test.SayHelloResponse")
    @Action(input = "http://soap_test.ats.uab.codes/TestWebService/sayHelloRequest", output = "http://soap_test.ats.uab.codes/TestWebService/sayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
