
package codes.uab.ats.soap_test;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestWebServiceService", targetNamespace = "http://soap_test.ats.uab.codes/", wsdlLocation = "http://homeplace:8081/soap-test/wsdl/TestWebServiceService.wsdl")
public class TestWebServiceService
    extends Service
{

    private final static URL TESTWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTWEBSERVICESERVICE_EXCEPTION;
    private final static QName TESTWEBSERVICESERVICE_QNAME = new QName("http://soap_test.ats.uab.codes/", "TestWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://homeplace:8081/soap-test/wsdl/TestWebServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTWEBSERVICESERVICE_WSDL_LOCATION = url;
        TESTWEBSERVICESERVICE_EXCEPTION = e;
    }

    public TestWebServiceService() {
        super(__getWsdlLocation(), TESTWEBSERVICESERVICE_QNAME);
    }

    public TestWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTWEBSERVICESERVICE_QNAME, features);
    }

    public TestWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, TESTWEBSERVICESERVICE_QNAME);
    }

    public TestWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTWEBSERVICESERVICE_QNAME, features);
    }

    public TestWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServicePort")
    public TestWebService getTestWebServicePort() {
        return super.getPort(new QName("http://soap_test.ats.uab.codes/", "TestWebServicePort"), TestWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestWebService
     */
    @WebEndpoint(name = "TestWebServicePort")
    public TestWebService getTestWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap_test.ats.uab.codes/", "TestWebServicePort"), TestWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTWEBSERVICESERVICE_EXCEPTION!= null) {
            throw TESTWEBSERVICESERVICE_EXCEPTION;
        }
        return TESTWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
